[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
ticketing_program = "tDdGYG37gZufntQqs7ZPuiSRyrceNP5ZdygqVQLjUGw"


[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
#rpc = "https://tyo74.nodes.rpcpool.com"

[scripts]
initialize = "ts-node migrations/initialize.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
